### PR TITLE
Simplify clientHook's refcounting scheme.

### PR DESCRIPTION
**Pull request by zenhack**
There is no actual reason why we need separate refcounts for calls and clients. In preparation for generally unifying the refcounting in this library, I've decided we should just merge them.

### CODE REVIEW

**Review by lthibault — APPROVED** [review]
LGTM.  Note that I have not looked at CI failure.

**Comment by zenhack** [comment]
I merged in #502, which fixed the test failures locally, so hopefully it should do so in CI as well. That PR should be reviewed & merged first.

**Comment by zenhack** [comment]
#348, re-running.

**Review by lthibault — DISMISSED** [review]
Approved (pending questions in #502)

**Review by lthibault — APPROVED** [review]

**Comment by zenhack** [comment]
Per my long rambly rubber-ducking session on matrix, there *is* a reason for having two separate refcounts: if refs hits zero Client.Release() will block on calls hitting zero before returning. This patch breaks that, oops. Closing.

**Pull request closed without merging**
