### PR TITLE
Fix build error on go1.23rc1

### PR DESCRIPTION
**Pull request by saschagrunert**
Can be tested with:

```bash
podman run -v $PWD:/w -w /w -it fedora:rawhide bash -c "dnf install -y go git && go build ./..."
```

Fixes https://github.com/capnproto/go-capnp/issues/575

### CODE REVIEW

**Comment by kwilczynski** [comment]
Looks good! Thank you for a swift fix!

/approve
/lgtm

**Review by lthibault — APPROVED** [review]
Hey, nice catch!  

Apologies for taking so long to review.  I am slowly spinning back up on capnp, so expecting to be more responsive going forward.

Thanks for submitting this!

**Comment by kwilczynski** [comment]
@lthibault, thank you!

It would be great to get a new release with this fix. Do you have some plans around that? We would be much obliged.

**Comment by lthibault** [comment]
@kwilczynski My pleasure!   [Here](https://github.com/capnproto/go-capnp/releases/tag/v3.0.1-alpha.2) is release v3.0.1-alpha.2

**Pull request merged**
